### ISSUE TITLE
partOfBeyondWordEmbedding.npy 这个文件包含的是所有的concept的向量吗

### ISSUE THREAD

**Issue by a-home-bird** [LittleGuoKe/ConceptFERE#1]
entities2id.pickle包含的是预训练原文中所有的entity吗

**Comment by LittleGuoKe** [comment]
没有包含原文中所有的实体，这个是ConceptGraph中的实体。原文中的小部分实体在ConceptGraph中是没有对应的概念的。

**Comment by LittleGuoKe** [comment]
在ConcptGraph中找不到概念的实体，这些实体的概念统一赋值为unknown
