### ISSUE TITLE
data获取失败

### ISSUE THREAD

**Issue by paxyqi** [LittleGuoKe/ConceptFERE#4]
你好，我从北航网盘下载数据，每次都在66%的时候失败。请问是否是数据源出问题了呢？

**Comment by paxyqi** [comment]
2022-07-08 13:40:50 (4.46 MB/s) - Connection closed at byte 4224021211. Retrying.

**Comment by LittleGuoKe** [comment]
问题不大，等我查一哈问题在哪，尽快给你一个可以下载的链接。

**Comment by LittleGuoKe** [comment]
问题已经解决，你可以在README.md中点击GOOLE DRIVE下载

**Comment by paxyqi** [comment]
> 

感谢您的回复，但我似乎无法下载，您是否设置了用户权限呢？

_访问 doc-0o-4o-docs.googleusercontent.com 被拒绝你没有查看此页面的用户权限。
HTTP ERROR 403_
这是我尝试下载时的效果。

**Comment by paxyqi** [comment]
BUPT的服务器连接google drive可能不太方便，如果您有时间可以发到我的邮箱吗？万分感谢。
_pixy_qi@qq.com_

**Comment by LittleGuoKe** [comment]
我这边测试让其它同学点击谷歌网盘是能够正常下载的，问题出在你那边（这个你得自己解决）。qq邮箱我会尝试给你发送。

**Comment by LittleGuoKe** [comment]
我看一哈邮箱发送方式，由于我们的文件很大有它们发送比较麻烦，我可以给你提供两个思路：第一：你可以试试从北航云盘上打开文件夹，把里面的文件一个一个下载，别一次下载所有。第二：你翻墙上谷歌云盘下载这个文件。
如果还不行，你再联系我吧。
